// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordsA;

namespace WordsA.Migrations
{
    [DbContext(typeof(Words))]
    partial class WordsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("WordsA.Tabela", b =>
                {
                    b.Property<int>("TabelaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WordEng")
                        .HasColumnType("TEXT");

                    b.Property<string>("WordPol")
                        .HasColumnType("TEXT");

                    b.HasKey("TabelaId");

                    b.ToTable("Slownik");
                });
#pragma warning restore 612, 618
        }
    }
}
